# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=500, verbose_name='Identificador')),
                ('sinopse', models.TextField(blank=True, null=True, verbose_name='Sinopse')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Iníco')),
                ('final_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Final')),
                ('season', models.CharField(blank=True, max_length=10, null=True, verbose_name='Temporada')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('episodes', models.IntegerField(blank=True, null=True, verbose_name='Número de Episódios')),
                ('a_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='animes/images', verbose_name='Imagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Animes',
                'verbose_name': 'Anime',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Gêneros',
                'verbose_name': 'Gênero',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo_anime.Genero', verbose_name='Gênero'),
        ),
    ]
